variables:
  STORAGE_DRIVER: vfs
  BUILDAH_FORMAT: docker

build:
  stage: build
  image: quay.io/buildah/stable
  tags: ["docker"]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah build -t $CI_REGISTRY_IMAGE:latest docker
    - buildah push $CI_REGISTRY_IMAGE:latest
